-- SELECT * FROM FILM
-- WHERE TITLE LIKE '%n'
-- ORDER BY LENGTH DESC
-- LIMIT 5;

-- SELECT * FROM FILM
-- WHERE TITLE LIKE '%n'
-- ORDER BY LENGTH
-- LIMIT 5
-- OFFSET 5;

SELECT * FROM CUSTOMER
WHERE STORE_ID = 1
ORDER BY LAST_NAME DESC 
LIMIT 4;